services:
  silencecut:
    image: visionugc.fr/silencecut:latest
    container_name: silencecut
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.silencecut.rule=Host(`silencecut.com`)"
      - "traefik.http.routers.silencecut.entrypoints=websecure"
      - "traefik.http.routers.silencecut.tls=true"
      - "traefik.http.routers.silencecut.tls.certresolver=letsencrypt"
      - "traefik.http.services.silencecut.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-my_secret}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      - NEXT_PUBLIC_EMAIL=silencecut.pro@gmail.fr
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    
networks:
  web:
    external: true
